language: python
python:
  - "3.6"
node_js:
  - "8.10"
before_install:
    - pip install pytest pytest-cov
    - pip install coverage
    - pip install codecov
install:
  - cd $TRAVIS_BUILD_DIR/application-server/ && pip install -r requirements.txt
  - cd $TRAVIS_BUILD_DIR/shared-server/ && npm install
  - cd $TRAVIS_BUILD_DIR/shared-server/ && npm install -g istanbul
script:
  - cd $TRAVIS_BUILD_DIR/application-server/ 
  - python example.py &
  - cd $TRAVIS_BUILD_DIR/application-server/test/ && py.test --cov=$(pwd)
  - cd $TRAVIS_BUILD_DIR/shared-server/ && npm test
after_success:
  - codecov --cov=./
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
