language: node_js
node_js:
  - "8.10"
install:
  - cd $TRAVIS_BUILD_DIR/shared-server/ && npm install
script: 
  - cd $TRAVIS_BUILD_DIR/shared-server/ && npm test
language: python
python:
  - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - cd $TRAVIS_BUILD_DIR/application-server/ && pip install -r requirements.txt
script:
  - cd $TRAVIS_BUILD_DIR/application-server/test/ && py.test
after_success: coveralls


