matrix:
  include:
    - language: python
      python: 3.6
      services:
        - mongodb
      before_install:
        - pip install pytest pytest-cov
        - pip install codecov
      install:
        - cd $TRAVIS_BUILD_DIR/application-server/ && pip install -r requirements.txt
      script:
        - cd $TRAVIS_BUILD_DIR/application-server/
        - export MONGO_URI=mongodb://localhost:27017/appserverdb
        - export SHARED_URI=http://172.17.0.1:8081/api
        - cd $TRAVIS_BUILD_DIR/docker/mongo/
        - ./docker-entrypoint.sh
        - python app.py &
        - cd $TRAVIS_BUILD_DIR/application-server/test/ && pytest --cov=./
        - codecov
    - language: android
      jdk: oraclejdk8
      env:
        - ANDROID_TARGET=android-22
        - ANDROID_ABI=armeabi-v7a
      android:
        components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-26
        - extra-android-m2repository
        - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
      before_install:
        - yes | sdkmanager "platforms;android-27"
      script:
        - cd $TRAVIS_BUILD_DIR/android-app/
        - ./gradlew build assembleAndroidTest
        - ./gradlew test

    - language: node_js
      node_js:
        - "8.10"
      install:
        - cd $TRAVIS_BUILD_DIR/shared-server/ && npm install
        - npm install -g istanbul
        - npm install -g codecov
      script:
        - cd $TRAVIS_BUILD_DIR/shared-server/ && npm test
        - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
        - codecov

    - language: node_js
      node_js:
        - "7"
      sudo: true
      dist: trusty

      before_script:
      - export CHROME_BIN=/usr/bin/google-chrome
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get update
      - sudo apt-get install -y libappindicator1 fonts-liberation
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo dpkg -i google-chrome*.deb

      script: 
        - cd $TRAVIS_BUILD_DIR/web/ && npm install
        - ng test --watch false -cc
        - npm run e2e
