APPLICATION_OWNER  = 'app1'
MONGODB_USER	   = 'app_user'
MONGODB_PASSWD	   = 'app_pass'
FCM_SERVER_KEY     = 'AAAAnYh-jwQ:APA91bEdEcM0FCm0zWBXl6DFUhADOmlDUuX3sgmrQFMFZj1oaOc93Ic1F2X6-TEF0bQtvexhA3THURa5n5_ZyCpK2hi9m0HTpHNeyqOiSUqneTPU7fkQnu69hPsrNrDt9jXMEh4ZGLsO'
API_KEY			   = 'defaultToken'
JWT_SECRET		   = 'tokenSecret'
