swagger: '2.0'
info: 
  description: API para el application server de Stories
  title: Stories - Application Server API
  version: 1.0.0
schemes: 
  - http
basePath: /api
consumes: 
  - application/json
produces: 
  - application/json
securityDefinitions:
  BusinessToken:
    type: apiKey
    in: query
    name: token
  ApplicationToken:
    type: apiKey
    in: query
    name: token
tags:
  - name: user
    description: |
      Llamados que puede realizar los usuarios 
paths:
  /token:
    post:
      tags:
        - user
      description: "Endpoint para generar un token para utilizar en los servicios del sistema (login)"
      parameters: 
        - description: "Datos para generar token"
          in: body
          name: body
          required: true
          schema: 
            $ref: '#/definitions/BusinessUserCredentials'
      responses: 
        201: 
          description: "Token generado correctamente"
          schema:
            properties:
              metadata:
                $ref: '#/definitions/EntityMetadata'
              token:
                $ref: "#/definitions/Token"
        400: 
          description: "Incumplimiento de precondiciones (parámetros faltantes)"
          schema: 
            $ref: "#/definitions/Error"
        401:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        500: 
          description: "Unexpected error"
          schema: 
            $ref: "#/definitions/Error"
      summary: "Generar token de usuario de negocio"      
            
definitions:
  Version:
    type: string
    description: Versión de la api
  Id:
    type: string
    description: |
      Se guarda como un string, pero podría ser un número
      es dependiente de la implementación.
  Timestamp:
    type: number
    description: |
      Tiempo en epoch      
  Ref:
    type: string
    description: |
      Hash que es utilizado para prevenir colosiones.
      Cuando se crea un elemento, se debe pasar un valor de undefined (o no debe estar).
      Al actualizar, el servidor chequeará que este valor sea igual al guardado, de no coincidir,
      significa que otro actualizó el recurso, por ende, la actualización debe fallar.
  Error: 
    properties: 
      code: 
        format: int32
        type: integer
      message: 
        type: string
    type: object
  EntityMetadata:
    properties:
      version:
        $ref: '#/definitions/Version'
  CollectionMetadata: 
    properties: 
      total:
        description: Cantidad de elementos existentes
        type: integer
      version: 
        $ref: '#/definitions/Version'
    type: object

  ApplicationUserCredentials:
    type: object
    properties: 
      username: 
        type: string
      password:
        description: Debe estar presente la contraseña o el token de fb.
        type: string
        format: password
      facebookAuthToken:
        type: string
        description: Token de autenticación de facebook. Debe estar presente la contraseña o el token de fb.
  CreateServerResponse:
    properties:
      server:
        $ref: '#/definitions/Server'
      token:
        $ref: '#/definitions/Token'
  Server:
    properties:
      id:
        $ref: '#/definitions/Id'
      _rev:
        $ref: '#/definitions/Ref'
      createdBy:
        $ref: '#/definitions/Id'
      createdTime:
        $ref: '#/definitions/Timestamp'
      name:
        type: string
        description: Nombre del application server
      lastConnection:
        $ref: '#/definitions/Timestamp'
  BusinessUserCredentials:
    properties:
      username:
        type: string
      password:
        type: string
        format: password
  Token:
    properties:
      expiresAt:
        $ref: '#/definitions/Timestamp'
      token:  
        type: string
        description: Token de autenticación
  ApplicationUser: 
    properties:
      id:
        $ref: '#/definitions/Id'
      _rev:
        $ref: '#/definitions/Ref'
      applicationOwner:
        $ref: '#/definitions/Id'
      username: 
        description: Nombre del usuario en la aplicación
        type: string
        
      
        